WHY TENSORS?

In [9]:
import time
import torch
import numpy as np

rows, cols = 100, 100

li = [[float(j) for j in range(cols)] for i in range(rows)]

start = time.perf_counter()

for r in range(rows):
    for c in range(cols):
        li[r][c] *= li[r][c]
end = time.perf_counter()

list_time = end - start
print(f"Python List (2D) Time: {list_time:.5f} seconds")

arr = np.zeros((rows, cols))

start1 = time.perf_counter()
arr = arr * arr
end1 = time.perf_counter()

numpy_time = end1 - start1
print(f"NumPy Tensor (2D) Time: {numpy_time:.5f} seconds")

tensor = torch.randn(rows, cols)

start2 = time.perf_counter()
tensor *= tensor
end2 = time.perf_counter()

torch_time = end2 - start2
print(f"PyTorch Tensor (2D) Time: {torch_time:.5f} seconds")


Python List (2D) Time: 0.00335 seconds
NumPy Tensor (2D) Time: 0.00027 seconds
PyTorch Tensor (2D) Time: 0.00021 seconds


TENSORS

In [10]:
import numpy as np

ln_1 = np.array([1, 2, 3])
ln_2 = np.array([[1, 2, 3], [4, 5, 6]])
ln_3 = np.zeros((2, 2, 2))

print(ln_1)
print(ln_2)
print(ln_3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [11]:
import torch

lt_1 = torch.tensor([4, 5, 6])
lt_2 = torch.tensor([[1, 2, 3],[1, 2, 3]])
lt_3 = torch.zeros(2, 3, 4)

print(lt_1)
print(lt_2)
print(lt_3)

tensor([4, 5, 6])
tensor([[1, 2, 3],
        [1, 2, 3]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


BASIC OPERATIONS

In [12]:
lt_4 = torch.tensor([1, 2, 3])

print(lt_1 + lt_4)
print(lt_4 * lt_1)
print(ln_1 ** 2)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
[1 4 9]


INDEXING AND SLICING

In [13]:
data = torch.tensor([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90],
                     [100, 110, 120]])

sub = data[:2, 1:]
print(sub)

mask = data > 50
print(data[mask])

tensor([[20, 30],
        [50, 60]])
tensor([ 60,  70,  80,  90, 100, 110, 120])


RESHAPING AND DIMENSIONALITY

In [14]:
print(data.view(2, 6))

print(data.reshape(2, 6))

a =data.unsqueeze(1)
print(a)

b = data.squeeze()
print(b)

tensor([[ 10,  20,  30,  40,  50,  60],
        [ 70,  80,  90, 100, 110, 120]])
tensor([[ 10,  20,  30,  40,  50,  60],
        [ 70,  80,  90, 100, 110, 120]])
tensor([[[ 10,  20,  30]],

        [[ 40,  50,  60]],

        [[ 70,  80,  90]],

        [[100, 110, 120]]])
tensor([[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90],
        [100, 110, 120]])


BROADCASTING

In [15]:
lt_4 = lt_1 + lt_2
print(lt_4)

lt_5 = lt_1 * lt_2
print(lt_5)

tensor([[5, 7, 9],
        [5, 7, 9]])
tensor([[ 4, 10, 18],
        [ 4, 10, 18]])


INPLACE/OUT OF PLACE

In [16]:
t = torch.tensor([1.0, 2.0])

t_out = t.add(5.0)
print(f"Out-of-place ID:     {id(t_out)}")

t.add_(5.0)
print(f"In-place ID:         {id(t)}")

Out-of-place ID:     132345463375344
In-place ID:         132344639688448
